import {
  boundedMessageText,
  evidenceFor,
  identityValue,
  isObject,
  malformedEvidence,
  processEvidence,
  requireContextText,
  stringValue,
} from "./codex-events.js";
import type {
  CodexEventEvidence,
  NormalizedRuntimeEvent,
  NormalizedRuntimeEventType,
  NormalizedRuntimePayloadMap,
} from "./codex-events.js";
import type {
  RuntimeJsonlRecord,
  RuntimeProcessCompletion,
} from "./process-runner.js";

/**
 * Meta's Muse Code `exec --json` -> product events.
 *
 * Every shape here was read off ONE capture: `docs/muse-probe-2026-09-21/`,
 * 27 records from Muse Code 1.3.0-R3401.1 on Windows, produced by
 * `muse exec --provider echo --json`. The echo provider needs no account and
 * spends nothing, which is why it is the fixture source and why it should
 * stay the fixture source.
 *
 * `msp.schema.json` in that folder is the wire protocol of Muse's SERVER
 * mode, generated by the binary itself. It is not the exec record stream and
 * is not treated as evidence for it here.
 *
 * What was measured, and what it means below:
 *
 * - Every record is an envelope: `schema_version`, `id`, `stream{kind,id}`,
 *   `sequence`, `recorded_at`, `record_type`, `durability`, `causation_id`,
 *   `payload_type`, `payload`. What the record IS lives in `payload_type`;
 *   `record_type` only says whether it is an `event`, a `status` or a
 *   `reconciliation`, which is a durability distinction rather than a
 *   meaning one, so nothing here branches on it.
 * - `stream.kind` is `session` on every record of the capture, and
 *   `stream.id` is the session id -- the value `--session-id` takes back.
 *   It is known from the FIRST record, not only at the end.
 * - `recorded_at` is in MICROSECONDS. Nothing reads it: the occurredAt on
 *   these events is the host clock, as it is for every other adapter. It is
 *   named here so that whoever reaches for it next does not divide by the
 *   wrong thousand.
 * - Assistant text arrives as `run.output.delta` -> `payload.text`, and the
 *   terminal record repeats the whole answer in its own `text`. Only one
 *   delta appeared in the capture, so whether deltas APPEND or REPLACE is
 *   not established. Both readings are survived the same way: deltas append
 *   into one item, and the terminal's `text` then REPLACES it. Whichever the
 *   truth is, the thread ends up holding the runtime's own final answer
 *   exactly once.
 * - Work happens in TASKS, each with its own id, and start and finish are
 *   separate records: `task.lifecycle.proposed` -> `accepted` -> `scheduled`
 *   -> `side_effect_intent` -> `started` -> `completed`. Only `proposed`
 *   carries `task_kind`, so the kind is remembered from it.
 * - The three task kinds captured are `reminder.agent.skill-reminder`,
 *   `model.unknown.response` and `reminder.agent.verify-reminder`. Those are
 *   Muse's own machinery, not the person's work: the model turn, and two
 *   reminders around it. Drawing them as tool rows would fill a thread with
 *   scaffolding, so `model.*` and `reminder.*` are kept off the transcript.
 *   NO OTHER TASK KIND HAS EVER BEEN SEEN -- a real tool call under a real
 *   provider was never captured, because capturing one costs money. Anything
 *   that is not those two families becomes an ordinary tool row, which is a
 *   guess about the shape of rows, not about whether they exist.
 * - **A failed task does not fail the run.** The capture contains a
 *   `task.lifecycle.failed` -- "invalid run configuration: provider does not
 *   support base instructions" -- and `run.terminal.completed` still said
 *   `completed`. Reading any failure as a run failure would have reported
 *   that good run as broken.
 * - What ends a run is `run.terminal.*`, carrying `terminal`, `text` and
 *   `reason`. `completed` is the only terminal value observed; anything else
 *   is treated as a failure rather than assumed benign.
 * - stdout is pure JSONL. Muse's own notices -- the workspace root it chose,
 *   "Agent delegation: auto unavailable" -- go to stderr and are not records.
 */

export interface MuseInvocationContext {
  /** Product-owned run identifier. Never the provider's session id. */
  readonly runId: string;
  readonly missionId?: string;
  readonly requestedRouteId?: string;
  readonly resolvedRouteId?: string;
  readonly cliVersion?: string;
  /** Test seam and host clock. */
  readonly now?: () => Date;
}

export interface MuseEventNormalizer {
  readonly runtimeThreadId: string | undefined;
  readonly finalized: boolean;
  accept(record: RuntimeJsonlRecord): readonly NormalizedRuntimeEvent[];
  finish(completion: RuntimeProcessCompletion): readonly NormalizedRuntimeEvent[];
}

type JsonObject = Record<string, unknown>;

/**
 * Task kinds that are Muse talking to itself: the model turn, whose answer
 * already reaches the thread as output, and the reminders it schedules
 * around one. A person asked a question, and neither of these is an answer
 * to it.
 */
const MUSE_INTERNAL_TASK = /^(?:model|reminder)\./i;

export function museTaskIsInternal(taskKind: string | undefined): boolean {
  return taskKind !== undefined && MUSE_INTERNAL_TASK.test(taskKind);
}

/**
 * The session id to hand back to `--session-id`, or nothing.
 *
 * It is `stream.id`, and ONLY on a `session` stream. A run stream and a task
 * stream both carry an `id` in the same field shape, and either would look
 * like a thread id to a reader that did not check the kind -- and a resume
 * against a task id is a run that silently starts somewhere else.
 */
export function museSessionIdOf(parsed: JsonObject): string | undefined {
  const stream = isObject(parsed.stream) ? parsed.stream : undefined;
  if (stream === undefined) return undefined;
  if (stringValue(stream.kind) !== "session") return undefined;
  return identityValue(stream.id);
}

/**
 * Meta refusing to answer until the account's payment method is verified.
 *
 * MEASURED 2026-09-25, muse 1.4.0: every run, whatever its flags, ended
 * `run.terminal.failed` with the reason "API error 402 [request_id=...]:
 * Billing verification failed. Please check your payment method.
 * (billing_error)", and the person was shown that line after "Muse Code ended
 * failed:" -- which reads as the app breaking, over something only their Meta
 * account can settle.
 */
const MUSE_BILLING_REFUSAL = /\bbilling_error\b|\bAPI error 402\b|billing verification failed/i;

export const MUSE_BILLING_SENTENCE =
  "Meta will not run Muse Code until the account's payment method is verified (API error 402, billing_error), so nothing in this run happened. That is settled in your Meta account, not in Locust.";

export function createMuseEventNormalizer(
  context: MuseInvocationContext,
): MuseEventNormalizer {
  const runId = requireContextText(context.runId, "runId");
  const cliVersion = context.cliVersion === undefined
    ? undefined
    : requireContextText(context.cliVersion, "cliVersion");
  const now = context.now ?? (() => new Date());

  let runtimeThreadId: string | undefined;
  let normalizedSequence = 0;
  let finalized = false;
  let runOpen = false;
  /** The `terminal` word of `run.terminal.*`, once one arrives. */
  let terminal: string | undefined;
  let terminalReason: string | undefined;
  /** Everything the deltas have said, so a terminal without text still has it. */
  let streamedText = "";
  let messageClosed = false;
  /** `task_kind`, which only `proposed` carries, kept by task id. */
  const taskKinds = new Map<string, string>();
  /** `operation`, from `side_effect_intent`: what the task is about to do. */
  const taskOperations = new Map<string, string>();

  const MESSAGE_ITEM = "msg_0";

  const emit = <TType extends NormalizedRuntimeEventType>(
    type: TType,
    payload: NormalizedRuntimePayloadMap[TType],
  ): NormalizedRuntimeEvent => {
    normalizedSequence += 1;
    return {
      id: `${runId}:muse:${normalizedSequence}`,
      runId,
      ...(context.missionId === undefined ? {} : { missionId: context.missionId }),
      sequence: normalizedSequence,
      occurredAt: now().toISOString(),
      sourceAdapter: "muse",
      ...(cliVersion === undefined ? {} : { cliVersion }),
      ...(context.requestedRouteId === undefined ? {} : { requestedRouteId: context.requestedRouteId }),
      ...(context.resolvedRouteId === undefined ? {} : { resolvedRouteId: context.resolvedRouteId }),
      ...(runtimeThreadId === undefined ? {} : { runtimeThreadId }),
      type,
      payload,
    } as NormalizedRuntimeEvent;
  };

  const diagnostic = (
    level: "info" | "warning" | "error",
    code: string,
    message: string,
    evidence: CodexEventEvidence,
  ): NormalizedRuntimeEvent =>
    emit("adapter.diagnostic", { level, code, message, terminal: false, evidence });

  /** The tool row for a task, from whatever the stream has said about it. */
  const toolRow = (taskId: string): {
    readonly itemId: string;
    readonly toolKind: string;
    readonly name: string;
    readonly command?: string;
  } => {
    const kind = taskKinds.get(taskId) ?? "task";
    const operation = taskOperations.get(taskId);
    return {
      itemId: taskId,
      toolKind: kind,
      name: kind,
      ...(operation === undefined ? {} : { command: boundedMessageText(operation) }),
    };
  };

  function acceptTask(
    payload: JsonObject,
    evidence: CodexEventEvidence,
  ): readonly NormalizedRuntimeEvent[] {
    const event = isObject(payload.event) ? payload.event : {};
    // The id sits on the event and again on the payload; either will do, and
    // taking both means a record that carries only one is still usable.
    const taskId = identityValue(event.task_id) ?? identityValue(payload.task_id);
    if (taskId === undefined) return [];
    const kind = stringValue(event.kind);

    if (kind === "proposed") {
      const taskKind = stringValue(event.task_kind);
      if (taskKind !== undefined) taskKinds.set(taskId, taskKind);
      return [];
    }
    if (kind === "side_effect_intent") {
      const operation = stringValue(event.operation);
      if (operation !== undefined) taskOperations.set(taskId, operation);
      return [];
    }
    // `accepted` and `scheduled` say a task moved through a queue. A person
    // watching wants to know it RAN, which `started` says.
    if (kind === "accepted" || kind === "scheduled") return [];

    const internal = museTaskIsInternal(taskKinds.get(taskId));

    if (kind === "started") {
      if (internal) return [];
      return [emit("tool.started", { ...toolRow(taskId), phase: "started", evidence })];
    }
    if (kind === "completed") {
      if (internal) return [];
      return [emit("tool.completed", { ...toolRow(taskId), phase: "completed", evidence })];
    }
    if (kind === "failed") {
      const reason = stringValue(event.reason);
      // A failed task is NOT a failed run -- see the note at the top of this
      // file, and the capture that proves it. Nothing here touches the run's
      // outcome; an internal failure is recorded as something that happened,
      // and the person's own tool rows fail on their own row.
      if (internal) {
        const named = taskKinds.get(taskId) ?? "a task";
        return [
          diagnostic(
            "info",
            "muse.internal_task_failed",
            reason === undefined
              ? `Muse Code's own ${named} did not run.`
              : `Muse Code's own ${named} did not run: ${reason}`,
            evidence,
          ),
        ];
      }
      return [
        emit("tool.failed", {
          ...toolRow(taskId),
          ...(reason === undefined ? {} : { status: reason }),
          phase: "completed",
          evidence,
        }),
      ];
    }
    return [
      diagnostic("info", "muse.unknown_task_state", `Unhandled Muse task state: ${kind ?? "none"}`, evidence),
    ];
  }

  function acceptParsed(
    record: RuntimeJsonlRecord,
    parsed: JsonObject,
  ): readonly NormalizedRuntimeEvent[] {
    const payloadType = stringValue(parsed.payload_type);
    if (payloadType === undefined) return [];
    runtimeThreadId = runtimeThreadId ?? museSessionIdOf(parsed);
    const payload = isObject(parsed.payload) ? parsed.payload : {};
    const evidence = evidenceFor(record, parsed, payloadType);

    // Bookkeeping the person has no stake in: which command was accepted,
    // which run belongs to it, which task stream was opened. None of it says
    // anything happened that a transcript should show.
    if (
      payloadType === "runtime.command.accepted"
      || payloadType === "session.run.linked"
      || payloadType === "task.stream.linked"
    ) {
      return [];
    }

    // The prompt, read back to us. The ledger already holds the person's own
    // words; recording these would put their question in the thread twice.
    if (payloadType === "turn.input.user") return [];

    if (payloadType === "run.lifecycle.started") {
      if (runOpen) return [];
      runOpen = true;
      return [emit("step.started", { stepKind: "turn", evidence })];
    }

    if (payloadType === "run.output.delta") {
      const text = stringValue(payload.text);
      if (text === undefined) return [];
      streamedText += text;
      return [
        emit("message.delta", {
          itemId: MESSAGE_ITEM,
          operation: "append",
          text: boundedMessageText(text),
          final: false,
          evidence,
        }),
      ];
    }

    if (payloadType.startsWith("task.lifecycle.")) return acceptTask(payload, evidence);

    if (payloadType.startsWith("run.terminal.")) {
      terminal = stringValue(payload.terminal) ?? payloadType.slice("run.terminal.".length);
      terminalReason = stringValue(payload.reason);
      const events: NormalizedRuntimeEvent[] = [];
      // The answer, whole, from the runtime's own last word. This REPLACES
      // whatever the deltas built, which is what makes it safe not to know
      // whether they appended or replaced.
      const finalText = stringValue(payload.text) ?? (streamedText.length > 0 ? streamedText : undefined);
      if (finalText !== undefined && !messageClosed) {
        messageClosed = true;
        events.push(
          emit("message.delta", {
            itemId: MESSAGE_ITEM,
            operation: "replace",
            text: boundedMessageText(finalText),
            final: true,
            evidence,
          }),
        );
      }
      if (runOpen) {
        runOpen = false;
        events.push(emit("step.completed", { stepKind: "turn", evidence }));
      }
      return events;
    }

    return [
      diagnostic("info", "muse.unknown_event", `Unhandled Muse record: ${payloadType}`, evidence),
    ];
  }

  return {
    get runtimeThreadId() {
      return runtimeThreadId;
    },
    get finalized() {
      return finalized;
    },

    accept(record: RuntimeJsonlRecord): readonly NormalizedRuntimeEvent[] {
      if (finalized) return [];
      let parsed: unknown;
      try {
        // A leading byte-order mark is not part of any JSON value, and the
        // capture in `docs/muse-probe-2026-09-21/` has one because Windows
        // PowerShell put it there on redirect, not because Muse emits one.
        // Stripping it costs a character test and keeps a fixture-shaped
        // record from being reported as malformed.
        parsed = JSON.parse(record.raw.replace(/^\uFEFF/, "")) as unknown;
      } catch {
        return [
          diagnostic("warning", "muse.malformed_record", "A Muse Code record could not be parsed.", malformedEvidence(record)),
        ];
      }
      if (!isObject(parsed)) {
        return [
          diagnostic("warning", "muse.malformed_record", "A Muse Code record was not an object.", malformedEvidence(record)),
        ];
      }
      return acceptParsed(record, parsed);
    },

    finish(completion: RuntimeProcessCompletion): readonly NormalizedRuntimeEvent[] {
      if (finalized) return [];
      finalized = true;
      const process = processEvidence(completion);
      const thread = runtimeThreadId === undefined ? {} : { runtimeThreadId };
      if (completion.cancelled) {
        return [emit("run.cancelled", { ...thread, process })];
      }
      const finished = terminal === "completed";
      if (!finished || completion.exitCode !== 0) {
        return [
          emit("run.failed", {
            kind: "process-failed",
            // The host's own doing comes first: past the output cap it was
            // Locust that ended the run, and nothing the runtime said
            // afterwards describes that better. Then the runtime's terminal,
            // which names what it thought happened. An exit code is last,
            // because a number is not a reason.
            message: completion.outputLimitExceeded
              ? "Muse Code sent output faster than Locust could record it, so the run was stopped rather than leave a gap in its record. Sending it again usually works."
              : terminal === undefined
                ? "Muse Code ended without a record saying the run had finished."
                : !finished
                  ? terminalReason === undefined
                    ? `Muse Code ended ${terminal}.`
                    : MUSE_BILLING_REFUSAL.test(terminalReason)
                      ? MUSE_BILLING_SENTENCE
                      : `Muse Code ended ${terminal}: ${terminalReason}`
                  : `Muse Code exited with code ${String(completion.exitCode)}.`,
            ...thread,
            runtimeTerminal: terminal === undefined ? "missing" : finished ? "completed" : "failed",
            process,
          }),
        ];
      }
      return [emit("run.completed", { ...thread, process })];
    },
  };
}
